#!/bin/bash
SpawningPoolIP="$(docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" spawning-pool)"
docker container run -d --name lair -p 8080:80 -e WORDPRESS_DB_NAME=zerglings -e WORDPRESS_DB_HOST=$SpawningPoolIP:mysql -e WORDPRESS_DB_PASSWORD=Kerrigan wordpress
